### ISSUE TITLE
RadialBar using Full API

### ISSUE THREAD

**Issue by maluta** [dreamRs/apexcharter#1]
I'd like to create a view using multiple radial bars.

I successfully generate it using the following code: 

```
  s <- c('S1','S2','S3','S4','S5','S6','S7')
    t <- c('100','100','100','50','10','0','0')
    c <- data.frame(s,t)
    
    apexcharter::apex(data = c, type = "radial",
                      mapping = aes(x = seqs, y = t))
    
```
Output: 

![image](https://user-images.githubusercontent.com/23658/58763237-b0a36980-852e-11e9-8b3a-ccf0eb4c1209.png)

But when I try to use [Full API](https://github.com/dreamRs/apexcharter#full-api) I'm struggling to map the parameters. 

The following code **isn't working**

```
  apexcharter::apexchart() %>%
      ax_chart(type = "radialBar") %>%
      ax_plotOptions(radial = radialBar_opts(
        size = 6
      )) %>% 
      ax_series(
        list(
          data = t
        )
      ) %>%
      ax_xaxis(categories = s ) %>%
      ax_subtitle(text = "")
```
I would appreciate any tip in where am I going wrong?

**Comment by pvictor** [comment]
Hi,

You can use the following : 

```r
s <- c('S1','S2','S3','S4','S5','S6','S7')
t <- c('100','100','100','50','10','0','0')

apexchart() %>%
  ax_chart(type = "radialBar") %>%
  ax_plotOptions(radial = radialBar_opts(
    size = 200
  )) %>%
  ax_series2( t ) %>%
  ax_labels2( s ) %>%
  ax_subtitle(text = "")
```
Full API to the JavaScript API, so you can refer to the official documentation : https://apexcharts.com/javascript-chart-demos/radialbar-charts/multiple-radialbars/

Here you have to `ax_series2` and `ax_labels2` because data for pie and radial chart use vector and not list for data.

Victor

**Comment by maluta** [comment]
Thanks Victor!
