### ISSUE TITLE
Order bar chart from large to small

### ISSUE THREAD

**Issue by meersel** [dreamRs/apexcharter#24]
Hi ApexCharter Developer's team.

Can you please advice me how to order a bar chart output such that the bars are shown from large to small..

I have tried the following standard **ggplot2** way of doing this (see below) but this does not work for apexcharter.

 ###

data("mpg")
n_manufac <- count(mpg, manufacturer) %>% 
              mutate(manufacturer = fct_reorder(manufacturer,n))

apex(data = n_manufac,
     type = "bar",
     mapping = aes(x = manufacturer, y = n))

###

Kind regards,

Miguel

**Comment by pvictor** [comment]
Hello,

Currently `apex()` does not reorder the data, they are represented as they are.
To order the chart, you can add an `arrange` in your pipeline :

```r
library(apexcharter)
library(dplyr)
library(forcats)
data("mpg", package = "ggplot2")

n_manufac <- count(mpg, manufacturer) %>%
  mutate(manufacturer = fct_reorder(manufacturer, n)) %>% 
  arrange(desc(manufacturer)) # <--- sort your data

apex(
  data = n_manufac,
  type = "bar",
  mapping = aes(x = manufacturer, y = n)
)
```

Which gives

![image](https://user-images.githubusercontent.com/4415580/87927528-a3737200-ca83-11ea-833a-6dd7a7f4ed9a.png)

Victor

**Comment by meersel** [comment]
Hi Victor,

Thanks for your quick reply.

A simple and workable solution.


Kind regards,


Miguel Eersel
e-mail: m.eersel@outlook.com<mailto:m.eersel@outlook.com>
mobile(WhatsApp) + 597-864 2328

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by meersel** [comment]
HI Victor,

Is the Dynamic Series Update functionality available (see below)  in the R Apexcharter package ?

[cid:image003.png@01D6A802.2441A090]

If so, would you be so kind to provide me with an R code example how to use this ?


Thanks in advance.


Kind regards/Met vriendelijke groet,


Miguel (a fan of the apexcharter R package)
e-mail: m.eersel@outllook.com
