### ISSUE TITLE
unhcr_ts data missing

### ISSUE THREAD

**Issue by OGuggenbuehl** [dreamRs/apexcharter#3]
Thank you for this beautiful package. 
I was trying to follow the vignettes to learn more about the specifics of apexcharter, but "Advanced configuration examples" can not be knitted anymore, because `unhcr_ts` appears to be missing. I have tried substituting this dataset for the included unhcr_popstats_2017, without any success.

**Comment by pvictor** [comment]
Hello,
Thanks :) Which version do you use ? You might need to re-install package grom GitHub, e.g. : 

```r
devtools::install_github("dreamRs/apexcharter")
```

Victor
