### ISSUE TITLE
Group bug?

### ISSUE THREAD

**Issue by chriswweibo** [dreamRs/apexcharter#30]
I  use apex to draw scatter plot. But strange thing happened.
The iris dataset has 150 records.
Using` apex(iris,type = 'scatter', aes(x=Sepal.Length,y=Sepal.Width))`. the plot is right.
![image](https://user-images.githubusercontent.com/11674246/97560721-0af17400-1a1a-11eb-9317-a8b1949cd0d8.png)

But if group var is added, and using `apex(iris,type = 'scatter', aes(x=Sepal.Length,y=Sepal.Width,group=Species))`.
The scatters get few. 
![image](https://user-images.githubusercontent.com/11674246/97560743-104ebe80-1a1a-11eb-86f4-1696884631dc.png)

Is it a bug?

**Comment by pvictor** [comment]
Yes that's a bug, thanks for reporting it.

Victor

**Comment by pvictor** [comment]
Fixed on GitHub, I'll submit to CRAN soon.

Victor
