### ISSUE TITLE
add_vline with dates on the x-axis not working

### ISSUE THREAD

**Issue by meersel** [dreamRs/apexcharter#41]
Hi,

I want to a vertical line on my apexchart using the **add_vline()** function.
My x-axis displays dates.

I have converted the date value for position of the vertical line into a numeric value (I think that this is required), however no vertical line is displayed on the chart.

See example code below:

apexcharter::add_vline(value = **as.Date("2021-02-10") %>% as.numeric()**, 
                                    dash = 4, color = "red", label = "Hello")

Please advice how to solve this problem.

Looking forward to hear from you soon.

Met  vriendelijke groet,

Miguel

**Comment by pvictor** [comment]
Hello,

If you use date on x-axis, you should use `add_event` to draw a vertical line:

```r
library(apexcharter)
data("economics", package = "ggplot2")

apex(economics, aes(date, psavert), type = "line") %>% 
  add_event("2000-01-01", label = "Year 2000")
```
![image](https://user-images.githubusercontent.com/4415580/107503567-67783980-6b9a-11eb-946c-767a4e561e37.png)

Victor

**Comment by meersel** [comment]
Hi Victor,

Many thanks for your quick response.
Best regards,

Miguel Eersel
e-mail: m.eersel@outlook.com

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
