### ISSUE TITLE
ax_forecast_data_points() seems to be missing 

### ISSUE THREAD

**Issue by franolicr** [dreamRs/apexcharter#70]
There doesn't seem to be an ax_forecast_data_points() function that corresponds to the forecastDataPoints option (https://apexcharts.com/docs/options/forecastdatapoints/)

**Comment by pvictor** [comment]
Hello, indeed, there's one if you re-install from GitHub. An example:

```r
# add 5 predictions to data then plot it
data.frame(
  time = seq_len(53),
  lh = c(
    as.vector(lh),
    as.vector(predict(arima(lh, order = c(1,0,1)), 5)$pred)
  )
) %>% 
  apex(aes(time, lh), type = "line") %>% 
  ax_xaxis(type = "numeric") %>% 
  ax_forecast_data_points(count = 5)
```
 
![image](https://github.com/dreamRs/apexcharter/assets/4415580/aa6a7c26-e991-4e6d-8242-849f8a30e247)

**Comment by pvictor** [comment]
Available in the last CRAN version
